### ISSUE TITLE
crafting bug multi item recipes(custom crafting identifier items)

### ISSUE THREAD

**Issue by MummieSenpai** [mehboss/CustomRecipes#10]
**Server Version** paper-1.20.1-55.jar
**Plugin Version** CustomRecipes(v1.8.1).jar
**issue**
when trying to use a custom item using the build in Identifiers it is ignoring the amount count when trying to craft multiple items at once. it is simply just taking one item from the stack untill the amount is below the amount needed. 

as shown in this video. 
https://youtu.be/2homFYSJeuU

crafting recipe used in the video is in this haste bin
https://hastebin.com/share/ovevefiyab.yaml

**Comment by mehboss** [comment]
Just a bit more testing to do and then I will have this fixed in v.1.8.2. Shouldn't be much longer as I believe I have it resolved, I just want to test other items. Thank you for reporting!

**Comment by mehboss** [comment]
Hello again, I have done some testing. I believe this issue has been resolved. Please do not hesitate to let me know if you encounter any more issues. I will be attentive and fix them as soon as possible. Thank you for reporting and I apologize that this was overlooked!

Find the update here:
https://www.spigotmc.org/resources/%E2%96%BA%E2%96%BA-custom-crafting-recipes-1-8-x-1-20-x-per-recipe-perms-create-your-own-recipes-%E2%97%84%E2%97%84.36925/update?update=506500
