### ISSUE TITLE
[Feature Request]: Placeholder API

### ISSUE THREAD

**Issue by MummieSenpai** [mehboss/CustomRecipes#11]
would be nice to have placeholder API support for different parts of the plugin. with some documentation about the placeholders.
would also like to see examples of how to use them / explaining what each placeholder does on the wiki 

for  example 

%Placeholder.% 

explanation

example use case 

%next placeholder %

greetz 
Mummie

**Comment by mehboss** [comment]
Hello. Could you give me some clarification on what you mean by placeholder API support? What kind of placeholder support would you be looking for?

**Comment by mehboss** [comment]
You want me to integrate PAPI into CR so that you can use other plugin placeholders in the lore of the custom items? Is that what you mean?

**Comment by MummieSenpai** [comment]
> You want me to integrate placeholders into CR so that you can use other plugin placeholders in the lore of the custom items? Is that what you mean?

this and that i could  pull recipe's into for example a hologram. calling on %recipe% or using an identifier.

**Comment by mehboss** [comment]
Sounds good, will do! What other placeholders would you like to see, aside from %recipe%?

**Comment by MummieSenpai** [comment]
i edited my comment to make it a bit more clear. 

but recipe would be nice 
the identifier those 2 are on the top of my mind

**Comment by mehboss** [comment]
Got it. Just need clarification on what you mean by "so bein able to pull information from placeholders present in the plugin to call on." Call on how?

**Comment by MummieSenpai** [comment]
as in bein able to for example pull the information of the recipe out of the plugin for example items needed pattern ect. so you could display it with custom maps or holograms or custom gui's

**Comment by mehboss** [comment]
Sounds good. Thank you for the suggestions!

**Comment by MummieSenpai** [comment]
no problem and just wanted to say you  have done an amazing job with the plugin.
i feel a bit bad making you work so hard on fixing bugs that i found so far 😅

**Comment by mehboss** [comment]
haha no worries, keep em' coming! :)

**Comment by mehboss** [comment]
So is this what you are looking for as far as placeholders?
(where slot is replaced with the crafting table slot and recipename is replaced with the configFile name)
RECIPENAME_ingredient_SLOT - returns item material
RECIPENAME_ingredient_name_SLOT - returns name if any
RECIPENAME_ingredient_amount_SLOT - returns required amount
RECIPENAME_ingredient_identifier_SLOT - returns identifier if any

**Comment by mehboss** [comment]
Hello, this feature has been implemented. Find the update [here](https://www.spigotmc.org/resources/%E2%96%BA%E2%96%BA-custom-crafting-recipes-1-8-x-1-20-x-per-recipe-perms-create-your-own-recipes-%E2%97%84%E2%97%84.36925/update?update=508658). Please let me know as many placeholder ideas as you have so I can implement them.

Thank you!
