### ISSUE TITLE
small visual console bug

### ISSUE THREAD

**Issue by MummieSenpai** [mehboss/CustomRecipes#13]
### What happened?

when you do `/cr reload` the console spits out 
![cmd_mKJ4G7zRCg](https://github.com/mehboss/CustomRecipes/assets/28273585/7e4b6d5d-7559-494c-bd04-45f289d08993)
but at the moment we have over 7 recipe's 
it does load them correctly. if i check /cr book. and i am able to craft them all. 

### What was supposed to happen?

intended outcome is having the correct number display

### How do I reproduce this issue?

```bash
1. have over 7 custom recipes
2. use `/cr reload`
3. check console log
...
```

### Relevant log output

```shell
[21:14:34 INFO]: mummieman issued server command: /cr reload
[21:14:34 INFO]: Loaded 7 recipes
[21:14:54 INFO]: mummieman issued server command: /cr book
```

### Server Version

This server is running Paper version git-Paper-55 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: e4b40dd)

### Plugin Version

1.8.2

### Server Mode

Online Mode

### Issue Confirmation

- [X] I have downloaded and tried the latest version of custom recipes and the issue still persists.
- [X] I have provided sufficient information for the issue to be replicated.

**Comment by mehboss** [comment]
Hello.
This server log is server sided and I can not remove this message. I can avoid any confusion by adding a message that lets you know how many ACTUAL recipes were loaded in that can be handled by custom recipes though.

Thank you

**Comment by MummieSenpai** [comment]
that would be appreciated to see the command tell you how many are reloaded. 
but like i said just a visual bug not a high priority or anything ;)

**Comment by Valorless** [comment]
As another user of the plugin, and contributor, I can confirm this message is server side like Boss is saying :)

**Comment by mehboss** [comment]
Hello MummieSenpai,

[Please refer here for resolution](https://www.spigotmc.org/resources/%E2%96%BA%E2%96%BA-custom-crafting-recipes-1-8-x-1-20-x-per-recipe-perms-create-your-own-recipes-%E2%97%84%E2%97%84.36925/update?update=508247)

Thanks
