### ISSUE TITLE
issue with Placeable: false using multiple items in item stack. 

### ISSUE THREAD

**Issue by MummieSenpai** [mehboss/CustomRecipes#16]
### What happened?

when you have multiple items of a placeable block in a stack it ignores the flag. 
if you have 1 block in the stack of said item it works correctly. and spits out the msg in chat + it stops bein placed down. 
if you have mutiple of 1 in the item stack it ignores the flag and places down the block untill you reach 1 item left in the itemstack.

### What was supposed to happen?

if flag set to false it should no matter of the stack size block bein placed down.

### How do I reproduce this issue?

```bash
1.give yourself multiple of an placeable block 
2.try placing it down 
3. it fails to block bein placed down. 
...
```

### Server Version

This server is running Paper version git-Paper-72 (MC: 1.20.1)

### Plugin Version

V1.8.3

### Server Mode

Online Mode

### Issue Confirmation

- [X] I have downloaded and tried the latest version of custom recipes and the issue still persists.
- [X] I have provided sufficient information for the issue to be replicated.

**Comment by mehboss** [comment]
Hello, thank you for your patience. This issue has been resolved. Find the update [here](https://www.spigotmc.org/resources/%E2%96%BA%E2%96%BA-custom-crafting-recipes-1-8-x-1-20-x-per-recipe-perms-create-your-own-recipes-%E2%97%84%E2%97%84.36925/update?update=508658).
