### ISSUE TITLE
using metals/diamonds in a recipe disables vanilla recipe

### ISSUE THREAD

**Issue by MummieSenpai** [mehboss/CustomRecipes#18]
### What happened?

we made some custom recipes using iron, gold, or diamonds. 
as shown in the log output box. 

if we set the crafting recipe to `Shapeless: true` 
it blocks the vanilla recipe of a helmet.  of that material type so in this case an diamond helmet.

as a temp fix we put shapeless on false. to have not this issue. 

### What was supposed to happen?

intended outcome is for both recipes to work vanilla helmet and the custom recipe.

### How do I reproduce this issue?

```bash
1. put config as shown below in the Recipe folder
2. reload plugin
3. try to craft a diamond helmet. 
...
```

### Relevant Config File.

```shell
EnchantedDiamond:
  Enabled: true
  Item: diamond
  Item-Damage: none
  Amount: 1
  Ignore-Data: false
  Ignore-Model-Data: false
  Custom-Tagged: true
  Shapeless: true
  Identifier: Enchanted_Diamond
  Permission: crecipe.recipe.EDiamond
  Name: '&aEnchanted Diamond'
  Lore:
  - ''
  - '&4&lDO NOT PLACE ITEM'
  - ''
  - '&a&lUncommon Crafting Item'
  Hide-Enchants: true
  Enchantments:
  - DURABILITY:3
  ItemCrafting:
  - XDX
  - DDD
  - XDX
  Ingredients:
    D:
      Material: diamond
      Amount: 32
  Item-Flags: []
  Attribute: []
  Custom-Model-Data: none
  Placeable: true
```

### Server Version

paper 1.20.1

### Plugin Version

1.8.4

### Server Mode

Online Mode

### Issue Confirmation

- [X] I have downloaded and tried the latest version of custom recipes and the issue still persists.
- [X] I have provided sufficient information for the issue to be replicated.

**Comment by mehboss** [comment]
Hello,
We have received your report and will get working on a fix shortly. You can expect a resolution for this issue within 24-72 hours.

Thank you.

**Comment by mehboss** [comment]
Hello,
This issue has been resolved. If you encounter any issues please let me know. I have done minimal testing since I have been extremely busy lately.

I apologize for the wait and thank you for reporting. [Click here for the new update.](https://www.spigotmc.org/resources/%E2%96%BA%E2%96%BA-custom-crafting-recipes-1-8-x-1-20-x-per-recipe-perms-create-your-own-recipes-%E2%97%84%E2%97%84.36925/updates)

Closed with the status of resolved.
