### ISSUE TITLE
Wrong item as the output.

### ISSUE THREAD

**Issue by AlmarBlock** [mehboss/CustomRecipes#19]
### What happened?

I created a crafting recipe and it was supposed to make a tripwire hook with a name and a lore, but It only made 9 Iron Nuggets.

ps. I use CloudNet V.4. and because of that BungeeCord.
Sorry for the Englisch (:

### What was supposed to happen?

The recipe should give me a Tripwire Hook that locks like that: 
![image](https://github.com/mehboss/CustomRecipes/assets/98546933/28192690-e313-479a-b3e0-36b1e1b35103)
(This one is optaint by the command: `/crecipe give <PLAYERNAME> Magnet`)

### How do I reproduce this issue?

1. Fresh install the Plugin.
2. Delete the the defulte recipes.
3. Create a new with the name: Magnet.yml
4. Fill the file with: ```https://pastebin.com/Bybz4MxH```
5. Run the reload command (```/crecipe reload```).
6. Try to craft it.

### Relevant log output

```shell
[05.08 23:00:36.872] INFORMATION: [Creativ-1] [23:00:36 INFO]: <PLAYERNAME> issued server command: /crecipe reload
[05.08 23:00:36.873] INFORMATION: [Creativ-1] [23:00:36 INFO]: Loaded 7 recipes
```

### Server Version

paper 1.20.1

### Plugin Version

1.8.5

### Server Mode

Offline Mode

### Issue Confirmation

- [X] I have downloaded and tried the latest version of custom recipes and the issue still persists.
- [X] I have provided sufficient information for the issue to be replicated.

**Comment by AlmarBlock** [comment]
![image](https://github.com/mehboss/CustomRecipes/assets/98546933/4c40266a-3a98-4841-9120-739f7ecd813d)
Here is a picture of the Crafting.

**Comment by mehboss** [comment]
Hello,I just want to let you know that i’ve received your report and will look into it further and provide an update for resolution within 24-72 hours. In the meantime, I suggest you to use the previous version (v1.8.4) as this should not be affected.Thank you,MehbossOn Aug 6, 2023, at 4:01 PM, Almar_Block ***@***.***> wrote:﻿

Here is a picture of the Crafting.

**Comment by ZayaJames** [comment]
Issue still happens with Lapis Lazuli as an ingredient turning custom recipe outputs into blue dye.

**Comment by mehboss** [comment]
Hey guys, I am working on a fix currently as we speak. Thank you for your patience!

**Comment by mehboss** [comment]
Hello guys! I have resolved this issue. If you encounter any other issues, please let me know and I will resolve it as quickly as possible. Thank you for your patience!

You can find the update [here](https://www.spigotmc.org/resources/%E2%96%BA%E2%96%BA-custom-crafting-recipes-1-8-x-1-20-x-per-recipe-perms-create-your-own-recipes-%E2%97%84%E2%97%84.36925/update?update=512206).

 Closed with a status of resolved.
