### ISSUE TITLE
Error occurred while enabling CustomRecipes v1.7.2-1.7.3

### ISSUE THREAD

**Issue by IvanVodkevich** [mehboss/CustomRecipes#2]
Dear MehBoss,
I _just_ created an account to reach out to you. I've been facing issues with many versions of your CustomRecipes plugin for Minecraft Paperspigot.
When I was starting the server up, these commands popped up:

_[15:59:58 INFO]: [CustomRecipes] Enabling CustomRecipes v1.7.2
[15:59:58 INFO]: [CustomRecipes] Made by MehBoss on Spigot. For support please PM me and I will get back to you as soon as possible!
[15:59:58 ERROR]: Error occurred while enabling CustomRecipes v1.7.2 (Is it up to date?)
[15:59:58 INFO]: [CustomRecipes] Disabling CustomRecipes v1.7.2_

How can I fix this? Do I need to try the older versions, or not?

**Comment by mehboss** [comment]
Hello, IvanVodkevich.
I am installing paper onto my test server and will get back to you shortly with a reply. Is that the only error that appears in the console on start up?

Thank you.

**Comment by mehboss** [comment]
Hello again, IvanVodkevich. I believe I may have fixed this issue, and so I will be closing this report. I apologize for this issue, and the resource update can be found [here](https://www.spigotmc.org/resources/%E2%96%BA%E2%96%BA-custom-crafting-recipes-1-8-x-1-19-x-per-recipe-perms-create-your-own-recipes-%E2%97%84%E2%97%84.36925/update?update=502609). I have tested this on paper 1.8-1.19 and all is well upon startup. Thank you for reporting this!

**Comment by IvanVodkevich** [comment]
So helpful <3
