### ISSUE TITLE
Problem While Making Recipe

### ISSUE THREAD

**Issue by retrowave115** [mehboss/CustomRecipes#20]
### What happened?

When I finish a recipe, and I restart the server, it says "Could not find configuration section CursedPickaxe in the recipe file: CursedPickaxe.yml - (CaSeSeNsItIvE) - Skipping this recipe" even though I did not delete any lines.

### What was supposed to happen?

I'm assuming it shouldn't do that and just load normally.

### How do I reproduce this issue?

```bash
1. I make a recipe
2. I restart the server
3. It says "Could not find configuration section CursedPickaxe in the recipe file: CursedPickaxe.yml - (CaSeSeNsItIvE) - Skipping this recipe"
```

### Relevant log output

```shell
Could not find configuration section CursedPickaxe in the recipe file: CursedPickaxe.yml - (CaSeSeNsItIvE) - Skipping this recipe
```

### Server Version

1.20 Paper

### Plugin Version

1.8.6

### Server Mode

Offline Mode

### Issue Confirmation

- [x] I have downloaded and tried the latest version of custom recipes and the issue still persists.
- [x] I have provided sufficient information for the issue to be replicated.

**Comment by retrowave115** [comment]
The error was copy and pasted from the minehut console.

**Comment by mehboss** [comment]
Hello, please provide the CursedPickaxe.yml in a pastebin link so I can take a look.

**Comment by retrowave115** [comment]
@mehboss Here is the pastebin: https://pastebin.com/PzuMT11j

**Comment by retrowave115** [comment]
I just looked at the wiki. So all I have to do is match the name on line 1 to the name of the yml file?

**Comment by mehboss** [comment]
Correct, match that to the name of the yml file and it will resolve your issue.

**Comment by retrowave115** [comment]
Ok, thank you.

**Comment by retrowave115** [comment]
It worked! Thanks.
