### ISSUE TITLE
[Feature Suggestion]: Recipes per world

### ISSUE THREAD

**Issue by EditChris** [mehboss/CustomRecipes#21]
### What is your suggestion?

Hi! As I explained on the SpigotMC forums, could you add an option to the recipe config file to make it only work on the worlds you indicate?

### Can you show some examples?

For example, if we have this in CursedPick.yml:

> EnabledWorlds:
> — survival_nether
> — hardcore

Then the recipe will only work in those two worlds of the whitelist. That would be the basic idea for it. There's also the option of doing it the opposite way and make it a blacklist, and also having something to enable the recipe everywhere as how it is right now.

### Beneficial to others?

This would be a godsent to have. It would give a lot of control over where to have what recipe in the server, allowing for an amazing customization potential. Some people won't need it yeah, but people like me that has on the same server different worlds with different mechanics, we would have a great time with this for sure.

### Server Version

Paper version git-Paper-117 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: 9bc70e6)

### Server Mode

None

**Comment by mehboss** [comment]
Hello EditChris,

I have implemented this amazing suggestion in the newest update which can be found [here.](https://www.spigotmc.org/resources/%E2%96%BA%E2%96%BA-custom-crafting-recipes-1-8-x-1-20-x-per-recipe-perms-create-your-own-recipes-%E2%97%84%E2%97%84.36925/update?update=512771) If you have any other suggestions or encounter any issues, please open up another ticket!

Thank you for using CustomRecipes,
Mehboss.
