### ISSUE TITLE
[Question]: Not sure If this is a bug or my fault 

### ISSUE THREAD

**Issue by BobTheKiller06** [mehboss/CustomRecipes#22]
### What is your question?

 I try making 2 recipe for an item like an iron chestplate, it seems to provide with me with only 1 result. Result = I am only able to use 1 recipe for 1 custom iron chestplate (respectively) to be crafted, the other recipe for another type of custom iron chestplate seems to not work. similar to the iron sword.

Not sure if its my fault or a bug, would appreciate help! 
Thanks

### Provide documentation

These are the basic ingredients used for crafting the recipe 
https://pastebin.com/BdDMuRXF 

these are the custom items that should be crafted
**iron_swords** 
https://pastebin.com/0YcwcXxG 

**iron_chestplates**
https://pastebin.com/eYH85vVu 

### Server Version

1.20

### Plugin Version

1.8.6

### Question Confirmation

- [x] I have checked the WIKI and the main page of the spigot resource, but still cannot find my answer.
- [X] I have provided sufficient information regarding my question.

**Comment by mehboss** [comment]
Hello, I apologize for this issue. It seems there is an issue within my code I am currently working to fix. I think I have it resolved, I just want to do some testing before I release this update to make sure nothing broke.

Thank you.

**Comment by mehboss** [comment]
If you would like to use it before I release it you may. I just want to take a little time to do some extra testing. Let me know if this fixed your issue!

You can find the download here:
https://www.dropbox.com/scl/fi/u5f799jmxxlrxgt4mbfzg/CustomRecipes-v1.8.7.jar?rlkey=devnwsi6hay49t4upfl1vuzl2&dl=0

**Comment by mehboss** [comment]
Hello There,

Once again, I apologize for this issue. It has now been resolved. You can find the resource update [here](https://www.spigotmc.org/resources/%E2%96%BA%E2%96%BA-custom-crafting-recipes-1-8-x-1-20-x-per-recipe-perms-create-your-own-recipes-%E2%97%84%E2%97%84.36925/update?update=512771). Let me know if you encounter any other issues, or have any other questions.

Closed with a status of resolved.

Thank you!

**Comment by BobTheKiller06** [comment]
Great!
Thanks, much appreciated!
