### ISSUE TITLE
[Question]: overriding a recipe 

### ISSUE THREAD

**Issue by MummieSenpai** [mehboss/CustomRecipes#29]
### What is your question?

i am aware overriding a recipe will remove the vanilla way of crafting it. 
this is what id like to do but can you give me an example of how to do it properly. 
as blacklisted.yml only has  
`override-recipes: []` 
but no example like it does with the vanilla recipes perm based option. 
do i need to put in the custom recipe identifier in there or do I need to add the new crafting recipe in there. 
for me in this case we want to make the crafting of end crystals more difficult.
instead of the eye of ender using a nether star. 

greetz Mummie 
we are enjoying your plugin so far keep up the good work

### Provide documentation

n/a

### Server Version

paper 1.20.1

### Plugin Version

latest

### Question Confirmation

- [X] I have checked the WIKI and the main page of the spigot resource, but still cannot find my answer.
- [X] I have provided sufficient information regarding my question.

**Comment by mehboss** [comment]
Hello, please refer here on the update information: https://www.spigotmc.org/resources/%E2%96%BA%E2%96%BA-custom-crafting-recipes-1-8-x-1-20-x-per-recipe-perms-create-your-own-recipes-%E2%97%84%E2%97%84.36925/update?update=505773

It utilizes item materials. Here is an example:

```override-recipes: # add vanilla material here if you plan on changing how you craft it
  - LAPIS_LAZULI```
