### ISSUE TITLE
[Feature Suggestion]: ecoenchant plugin support

### ISSUE THREAD

**Issue by MrFadeFancy** [mehboss/CustomRecipes#31]
### What is your suggestion?

Please support ecoenchants plugin 

### Beneficial to others?

Idk more custom enchantment plugin support

### Server Mode

Online Mode

**Comment by mehboss** [comment]
Hello there,
Added to my to-do list

Thank you.

**Comment by mehboss** [comment]
Feature has been added in latest update.
