### ISSUE TITLE
i cant dissabel netherite and thers an error with the leggins

### ISSUE THREAD

**Issue by Snic0509** [mehboss/CustomRecipes#32]
### What happened?

I wrote in the blacklist list 
Netherite_helmet and saved after that i reloadet the plgin but i can stimm craft it 

the secondthing is i addet Golden/diamond/iron_Leggins and when i reloadet the pluin i got an error that the item Golden_leggins dint match with an minecraft Item the error : ([19:17:05 ERROR]: [CustomRecipes] We are having trouble matching the material 'Golden_leggins' to a minecraft item. This can cause issues with the plugin. Please double check you have inputted the correct material ID into the blacklisted config file and try again. If this problem persists please contact Mehboss on Spigot!) but i cant craft it now ingame 

### What was supposed to happen?

Metherite Items schould be idissabeld and i shouldet be allowed to craft thje legins.

### How do I reproduce this issue?

```bash
1.i add leggins and relaod the plugin then i delete the leggins and reload now i cant craft the item
2. i add netherite but i can still craft it 
3.
...
```

### Relevant file configuration

```shell
[19:17:05 ERROR]: [CustomRecipes] We are having trouble matching the material 'Golden_leggins' to a minecraft item. This can cause issues with the plugin. Please double check you have inputted the correct material ID into the blacklisted config file and try again. If this problem persists please contact Mehboss on Spigot! 

Diamond_boots:
    permission: Rüstung-2
  Golden_helmet:
    permission: Rüstung-1
  Golden_chestplate:
    permission: Rüstung-1
  Golden_boots:
    permission: Rüstung-1
  Netherite_helmet:
    permission: Rüstung-3
```

### Server Version

1.20

### Plugin Version

1.8.7

### Server Mode

Online Mode

### Issue Confirmation

- [X] I have downloaded and tried the latest version of custom recipes and the issue still persists.
- [X] I have provided sufficient information for the issue to be replicated.

**Comment by mehboss** [comment]
Hello there,

The correct material IDs can be found here: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html

It is going to be GOLDEN_LEGGINGS not GOLDEN_LEGGINS
[NETHERITE_HELMET](https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html#NETHERITE_HELMET)

Please let me know if you need any additional help
