### ISSUE TITLE
[Question]: 

### ISSUE THREAD

**Issue by Snic0509** [mehboss/CustomRecipes#33]
### What is your question?

i nedd help with the enchantments on the custom items i add the enchantment but i cant see the enchantments on the items (hide enchantments is false) and it dosent change anything abolut the damage 

### Provide documentation

Aetheralitbrustpanzer:
  Enabled: true # Whether or not this recipe is enabled
  Shapeless: false # Whether or not you want it to have specific order in crafting
  Item: netherite_chestplate # Item ID
  Item-Damage: none # Used for when you need a specific type of item with a "19/00" or "13:4". leave to none if non exists.
  Amount: 1 # When you craft this item, this is the amount you will get from it.
  Placeable: true # If it is a block, you can choose to make it unplaceable.
  Ignore-Data: false # Whether or not metadata should be considered as a requirement for crafting
  Ignore-Model-Data: false # Whether or not you want model data to be considered even if ignore-data is set to true
  Custom-Tagged: true # Whether or not you want this item to be tagged with a custom item tag.
  Durability: '100' # 1-100. Remove section if not needed.
  Identifier: Aetheralitbrustpanzer # Give your new recipe an identifier :).
  Permission: crecipe.recipe.Aetheralit # Give a player this permission to allow them to craft this item. Remove section if no permission wanted.
  Name: &lAetheralitbrustpanzer # Name of the item, you can use color codes. Remove if not needed
  Lore:
  - '&c&lEin brustpanzer der den Goettern wuerdig sind'
  
  Hide-Enchants: false # Show enchants on item?
  Enchantments:
  - PROTECTION:5
  ItemCrafting:
  - IXI
  - IEI
  - III
  Ingredients:
    # DO NOT INCLUDE VARIABLE X AS AN INGREDIENT. THIS IS DEFAULTED TO AIR **
    E: # E is the letter I picked for emerald
      # REMOVE NAME SECTION OR SET TO 'none' IF NOT WANTED
      Material: netherite_ingot # Material ENUM
      Identifier: none # Set to custom recipe 'identifier' to use a custom item as an ingredient
      Amount: 1 # Amount required in one slot to craft
    I:
      Material: Diamond
      Identifier: none
      Amount: 1
  Item-Flags: []
  # Add items flags to your item such as hide attributes
  Attribute: []
  # Adds a given amount of a specified attribute to the custom item.
  # Format: ATTRIBUTE:AMOUNT:SLOT
  Custom-Model-Data: none
  Disabled-Worlds: []
# Custom model data for texture packs. Only on MC 1.14+!

### Server Version

1.20

### Plugin Version

1.8.7

### Question Confirmation

- [X] I have checked the WIKI and the main page of the spigot resource, but still cannot find my answer.
- [X] I have provided sufficient information regarding my question.

**Comment by mehboss** [comment]
Hello there Snic0509,

As you can see by the console log:
![image](https://github.com/mehboss/CustomRecipes/assets/17992070/79d03d2a-f320-40ed-8b4a-9145da55a1a8)
The enchantment PROTECTION is not a valid enchantment.

[Here is a list of all valid enchantments](https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/enchantments/Enchantment.html)
![image](https://github.com/mehboss/CustomRecipes/assets/17992070/6bc644b7-67e2-41c4-bf95-6cd834267839)

The enchantment you are looking for is
"PROTECTION_ENVIRONMENTAL"

For future reference - If you are having an issue with a particular feature, 99% of the time console will log what the issue is, especially when relating to enchantment issues.

Thank you,
Mehboss

**Comment by Snic0509** [comment]
Tahnk you very mutch

**Comment by Snic0509** [comment]
Where did you find the list ?

**Comment by Valorless** [comment]
Spigot has a massive docs detailing most of what can be used in terms of developing plugins for it.
The enchants themselves are here: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/enchantments/Enchantment.html

If I search on google for example "Spigot potion effects", one of the first results is a full list of all the potion effects available: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/potion/PotionEffectType.html
