### ISSUE TITLE
The gui from CustomRecipes doesn't work

### ISSUE THREAD

**Issue by Marleo122** [mehboss/CustomRecipes#34]
### What happened?

![Screenshot_1](https://github.com/mehboss/CustomRecipes/assets/143972687/116c5aca-0471-437e-abc1-281af46398fa)
Show this message whenever u used the command /crecipes gui and others

### What was supposed to happen?

open the gui of the plugin

### How do I reproduce this issue?

```bash
1.log in to ur mc server
2.use the command /crecipes gui
```

### Server Version

1.20

### Plugin Version

1.8.8

### Server Mode

Online Mode

### Issue Confirmation

- [X] I have downloaded and tried the latest version of custom recipes and the issue still persists.
- [X] I have provided sufficient information for the issue to be replicated.

**Comment by Valorless** [comment]
Greetings!
If I recall correctly, the in-game GUI used to manage custom recipes is still being created, and therefore unavailable to be used at this time. :)
I apologize for the inconvenience.
