### ISSUE TITLE
[Question]:  is there any changse that i could add a costem crating recipie fore the gringots money ?

### ISSUE THREAD

**Issue by Snic0509** [mehboss/CustomRecipes#36]
### What is your question?

Add the gringots money to the custom items
I addet the recipe bbbbut i cant stack it with the gingots money and i cant craft it with the Gringotts money and the anbotherthing is that i need one silmeball instead of 10

### Provide documentation

The gingotts config:
# value of individual denominations. default: emerald: 1, emerald block: 9
  denominations:
    - material: slime_ball
      value: 1
      unit-name: Sesterze
      unit-name-plural: Sesterzen
      displayname: §7Sesterze
    #      damage: 10
    #      custom_model_data: 1
      lore:
        - §aDie niedrigste Währungseinheit
    - material: magma_cream
      value: 9
      unit-name: Denar
      unit-name-plural: Denare
      displayname: §6Denar
#      damage: 10
#      custom_model_data: 1
      lore:
       - §aDie mittlere Währungseinheit
    - material: heart_of_the_sea
      value: 81
      unit-name: Aureus
      unit-name-plural: Aurei
      displayname: §bAureus
#      damage: 10
#      custom_model_data: 1
      lore:
        - §aDie höchste Währungseinheit
        
        
The recipe:
Denar:
  Enabled: true # Whether or not this recipe is enabled
  Shapeless: true # Whether or not you want it to have specific order in crafting
  Item: magma_cream # Item ID
  Item-Damage: none # Used for when you need a specific type of item with a "19/00" or "13:4". leave to none if non exists.
  Amount: 1 # When you craft this item, this is the amount you will get from it.
  Placeable: true # If it is a block, you can choose to make it unplaceable.
  Ignore-Data: false # Whether or not metadata should be considered as a requirement for crafting
  Ignore-Model-Data: false # Whether or not you want model data to be considered even if ignore-data is set to true
  Custom-Tagged: true # Whether or not you want this item to be tagged with a custom item tag.
  Identifier: Denar # Give your new recipe an identifier :).
  Permission: crecipe.recipe.default # Give a player this permission to allow them to craft this item. Remove section if no permission wanted.
  Name: '&6Denar' # Name of the item, you can use color codes. Remove if not needed
  Lore:
  - '&aDie mittlere Währungseinheit'
  
  Hide-Enchants: true # Show enchants on item?
  ItemCrafting:
  - XXE
  - XXX
  - XXX
  Ingredients:
    # DO NOT INCLUDE VARIABLE X AS AN INGREDIENT. THIS IS DEFAULTED TO AIR **
    E: # E is the letter I picked for emerald
      # REMOVE NAME SECTION OR SET TO 'none' IF NOT WANTED
      Material: slime_ball # Material ENUM
      Identifier: Sesterze # Set to custom recipe 'identifier' to use a custom item as an ingredient
      Amount: 10 # Amount required in one slot to craft
  Item-Flags: []
  # Add items flags to your item such as hide attributes
  Attribute: []
  # Adds a given amount of a specified attribute to the custom item.
  # Format: ATTRIBUTE:AMOUNT:SLOT
  Custom-Model-Data: none
  Disabled-Worlds: []
# Custom model data for texture packs. Only on MC 1.14+!

### Server Version

1.20

### Plugin Version

1.8.7

### Question Confirmation

- [X] I have checked the WIKI and the main page of the spigot resource, but still cannot find my answer.
- [X] I have provided sufficient information regarding my question.

**Comment by mehboss** [comment]
Hello there,
I am having trouble deciphering what exactly your issue is. Additionally, could you please paste your recipe file on pastebin.com and send the link so that it is easier to read.

Thank you,
Mehboss.

**Comment by Snic0509** [comment]
[Problem.txt](https://github.com/mehboss/CustomRecipes/files/12552063/Problem.txt)

Here is the FIle 

i try to make an crating recipe with the custom momey from gringotts but it dosent work also can i crat the item with one instead of 10 slimeballs
