### ISSUE TITLE
[Feature Suggestion]: GUI editor

### ISSUE THREAD

**Issue by MrFadeFancy** [mehboss/CustomRecipes#37]
### What is your suggestion?

It would be great to have a gui to create any recipe 

### Can you show some examples?

if I want to use a item that has a custom model data or nbt but idk what the nbt or model data of that item is, it would be great to just put that item in that gui

### Beneficial to others?

it would be easy to make custom recipe 

### Server Version

1.20.1

### Server Mode

Online Mode

**Comment by mehboss** [comment]
Hello! An update will be released soon allowing for more NBT options. Thank you!
