### ISSUE TITLE
How would I make tipped arrows craftable in a different maethod with this plugin

### ISSUE THREAD

**Issue by GTnoobGP** [mehboss/CustomRecipes#42]
### What is your question?

How would I make tipped arrows craftable in a different maethod with this plugin 

### Server Version

Neither

### Plugin Version

1.8.8

### Question Confirmation

- [X] I have checked the WIKI and the main page of the spigot resource, but still cannot find my answer.
- [X] I have provided sufficient information regarding my question.

**Comment by mehboss** [comment]
Hello! I will be implementing a release for more NBT options soon which should allow for this feature. You will be notified when it is released, hopefully sometime next week. Thank you!
