### ISSUE TITLE
[Question][Bug?]:recipes are full loaded, /cr give works, but i cant craft! 

### ISSUE THREAD

**Issue by TECHOPC** [mehboss/CustomRecipes#46]
### What is your question?

![image](https://github.com/mehboss/CustomRecipes/assets/34199654/b5bdaa32-fa76-4b5e-9940-261cfc8c3ef1)
![image](https://github.com/mehboss/CustomRecipes/assets/34199654/6e13680b-9bdd-4ad0-9ecb-9b87d500cb80)
![image](https://github.com/mehboss/CustomRecipes/assets/34199654/c97ea7f3-0bfb-411f-be23-fb02cda37a50)
![image](https://github.com/mehboss/CustomRecipes/assets/34199654/c0ce8ccd-fe37-420e-a924-2f51c0dcf774)
![image](https://github.com/mehboss/CustomRecipes/assets/34199654/49b44ca0-e1f0-4ee6-b642-5fc89074be81)

Discord: techo_pc

### Server Version

1.8.9 paper

### Plugin Version

CustomRecipes(v1.8.8).jar

### Question Confirmation

- [X] I have checked the WIKI and the main page of the spigot resource, but still cannot find my answer.
- [X] I have provided sufficient information regarding my question.

**Comment by mehboss** [comment]
Hello TechoPC!

I appreciate your bug report. Could you please perform a full restart of the server and copy your startup log (console) into a pastebin.com and then kindly provide me with the link so I can review it. 

This will help me to troubleshoot the issue to attempt a solution for you. 

Thank you!

**Comment by TECHOPC** [comment]
startup log \/
https://pastebin.com/Hd82U8vm

**Comment by mehboss** [comment]
Thank you for that. It is possible you have another plugin that is getting in the way of custom recipes. Could you try removing the other plugin(s) that have crafting features and see if this resolves your issue?

I will do some testing myself later, but i’m assuming this is the cause of it not working properly.

**Comment by TECHOPC** [comment]
deleted all other plugins and the 1.8.8 version still didnt work.

downloaded the "1.8.7 | Aug 12, 2023" version
now it works
![image](https://github.com/mehboss/CustomRecipes/assets/34199654/fbdfc218-2a72-4562-ab04-7225656c9a1a)

full log using CR 1.8.7
https://pastebin.com/sttRHDW3

**Comment by TECHOPC** [comment]
also worked well on the other server copy running all my other plugins
https://pastebin.com/YNbbic6f
![image](https://github.com/mehboss/CustomRecipes/assets/34199654/046f3a5b-0070-4f82-94e3-c1b999813b40)

**Comment by mehboss** [comment]
Hello, thank you for that. Not sure how I missed this. I believe I have fixed the issue. I am going to do some testing and I will let you know when the update is released.

Thank you.

**Comment by mehboss** [comment]
Hello again,
I have released fixes to the above issue AND tested it. I appreciate your patience while I was investigating and fixing it. I appreciate your report and thank you for using CR!!

Find the release [here.](https://www.spigotmc.org/resources/%E2%96%BA%E2%96%BA-custom-crafting-recipes-1-8-x-1-20-x-per-recipe-perms-create-your-own-recipes-%E2%97%84%E2%97%84.36925/update?update=539702)

Ticket closed.
