### ISSUE TITLE
[Question]: Crafting Dynamite

### ISSUE THREAD

**Issue by dinosrack** [mehboss/CustomRecipes#51]
### What is your question?

Can I create my own dynamite that will be N times stronger than usual? And also make an obsidian explosion?
I implemented this using a plugin (https://www.spigotmc.org/resources/tnt-crafting.102777 /) but it stopped working in conjunction with Custom Crafting Recipes

### Server Version

1.20.1

### Plugin Version

1.9

### Question Confirmation

- [X] I have checked the WIKI and the main page of the spigot resource, but still cannot find my answer.
- [X] I have provided sufficient information regarding my question.

**Comment by mehboss** [comment]
Hello dinosrack,
You can not create custom dynamite with custom recipes. I am sorry to hear that it does not work with tnt crafting. When you say it stopped working, do you mean that you can no longer craft the dynamite? I will look into this further for you and get back to you

Thank you

**Comment by mehboss** [comment]
CR resets all recipes and only works in conjunction with vanilla recipes as of right now. I will implement a change in the next release that will add support for other recipe plugins.

Thanks.
