### ISSUE TITLE
Ingredients Amount Stonecutter

### ISSUE THREAD

**Issue by Walabise** [mehboss/CustomRecipes#53]
### What happened?

The number of ingredients entered in the configuration is not taken into account in game. I would like to use the "StoneCutter" and have the possibility of putting a minimum number of ingredients to make the craft.

### What was supposed to happen?

As indicated in the config: 
To craft my item I would need 2 iron.
Gold in game the craft works with 1 of iron
![image](https://github.com/mehboss/CustomRecipes/assets/33760538/05fa07d8-d701-4bb1-9b7e-a43535c454f3)

### How do I reproduce this issue?

```bash
ItemCrafting:
  - IXX
  - XXX
  - XXX
  Ingredients:
    # DO NOT INCLUDE VARIABLE X AS AN INGREDIENT. THIS IS DEFAULTED TO AIR **
    I:
      Material: IRON_INGOT
      Identifier: none
      Amount: 2
```

### Relevant file configuration

```shell
test:
  Enabled: true # Whether or not this recipe is enabled
  Shapeless: false # Whether or not you want it to have specific order in crafting
  Item: PAPER # Item ID
  Item-Damage: none # Used for when you need a specific type of item with a "19/00" or "13:4". leave to none if non exists.
  Amount: 2 # When you craft this item, this is the amount you will get from it.
  Placeable: true # If it is a block, you can choose to make it unplaceable.
  Ignore-Data: false # Whether or not metadata should be considered as a requirement for crafting
  Ignore-Model-Data: false # Whether or not you want model data to be considered even if ignore-data is set to true
  Custom-Tagged: true # Whether or not you want this item to be tagged with a custom item tag.
  Identifier: test # Give your new recipe an identifier :).
  Converter: STONECUTTER # Set to FURNACE or STONECUTTER to create recipes for those tools.
  Name: test # Name of the item, you can use color codes. Remove if not needed
  Lore: []
  Effects: []
  Hide-Enchants: false # Show enchants on item?
  Enchantments: []
  ItemCrafting:
  - IXX
  - XXX
  - XXX
  Ingredients:
    # DO NOT INCLUDE VARIABLE X AS AN INGREDIENT. THIS IS DEFAULTED TO AIR **
    I:
      Material: IRON_INGOT
      Identifier: none
      Amount: 2
  Custom-Tags: []
  # Add specific NBT tags
  Item-Flags: []
  # Add items flags to your item such as hide attributes
  Attribute: []
  # Adds a given amount of a specified attribute to the custom item.
  # Format: ATTRIBUTE:AMOUNT:SLOT
  Custom-Model-Data: 10744
  # Custom model data for texture packs. Only on MC 1.14+!
  Disabled-Worlds: []
# Disable crafting in specific worlds
```

### Server Version

1.20.4

### Plugin Version

1.9

### Server Mode

Online Mode

### Issue Confirmation

- [X] I have downloaded and tried the latest version of custom recipes and the issue still persists.
- [x] I have provided sufficient information for the issue to be replicated.

**Comment by mehboss** [comment]
Hello Walabise,
I apologize for the miscommunication. Stonecutters only support one amount and one ingredient per recipe at this time. Instead of using two different configuration templates, I incorporated the same template for both types of recipes, thus the "amount" field.

Thank you
