### ISSUE TITLE
Cursor ItemStack is duplicated if same item as output and count is 32 or more.

### ISSUE THREAD

**Issue by Poikilos** [mehboss/CustomRecipes#56]
### What happened?

The output slot itemstack gets duplicate items if clicked with 32 or more of the same item.

I suggest testing for regression in related issues after fixing it:
- #55 (may be same handler, so fixing both this and that issue at once may be possible)
- #50 (not reproducible with 1.9.1 on Paper 1.20.4)

### What was supposed to happen?

The output itemstack is never supposed to be more than the output amount of one set of ingredients (usually 1, but is allowed to be a different number, such as how 6 cobblestone become 4 cobblestone stairs).

### How do I reproduce this issue?

```bash
1. Get 32 of output item in inventory (32 gravel in the case of the Gravel.yml below).
2. Place 1 or more of input item (cobblestone in this case) in any crafting grid.
3. Click the stack in inventory so there are 32 of output item in the cursor stack.
4. Click the output slot.

The output slot and the cursor stack both become 33.

This can occur with any number. For example:
- if you click the output slot when there are 64 in the cursor, you can get 65.
- You can only put 64 in an inventory slot
  - but you can click the output slot to get 66 in both the output stack and cursor stack (132 total).
  - Once you take the additional copies from the output slot, you keep the doubled (plus 2) number of items.
- You can repeat this process infinitely.
```

### Relevant log output

```shell
N/A
```

### Relevant file configuration

```shell
Gravel:
  Enabled: true
  Shapeless: true
  Item: GRAVEL
  Amount: 1
  Identifier: GRAVEL
  ItemCrafting:
  - CXX
  - XXX
  - XXX
  Ingredients:
    C:
      Material: COBBLESTONE
      Identifier: none
      Amount: 2
  Placeable: true
  Ignore-Model-Data: false
  Item-Flags: []
  Disabled-Worlds: []
```

Config.yml: Same as in #55

### Server Version

Paper 1.20.4

### Plugin Version

1.9.1

### Server Mode

Online Mode

### Issue Confirmation

- [X] I have downloaded and tried the latest version of custom recipes and the issue still persists.
- [X] I have provided sufficient information for the issue to be replicated.

**Comment by mehboss** [comment]
Hello Poikilos! 
I haven’t checked to see if this can be reproduced in versions prior to 1.20, but I know that I am waiting on a solution for an API bug that now exist in 1.20 and 1.21.

With this being said, the shift click and amount deductions are not working correctly in 1.19 and 1.20

The issue stems from:
https://hub.spigotmc.org/jira/plugins/servlet/mobile#issue/SPIGOT-7909

Thank you for reporting, I will get back to you later on today when I can get in front of my PC.

**Comment by Poikilos** [comment]
maybe some validation of the output (acquired in cursor, inventory, and/or dropped if inventory full) could be used to then validate the quantity in the output stack, or vise-versa. There is something like that trying to happen, but not quite working: When there is fewer than 32 in the cursor stack, a higher number (double whatever is held) flashes for one frame.

**Comment by mehboss** [comment]
This issue has also been resolved. The update will be released tomorrow.
Thank you for your patience

**Comment by mehboss** [comment]
I have done testing in 1.20, and all seems well. I have not tested paper or previous versions, but they should work. Thank you and I hope this resolves your issue.

https://www.spigotmc.org/resources/%E2%96%BA%E2%96%BA-custom-crafting-recipes-1-8-x-1-20-x-per-recipe-perms-create-your-own-recipes-%E2%97%84%E2%97%84.36925/update?update=563976
