### ISSUE TITLE
I have essential on my server 

### ISSUE THREAD

**Issue by ORZ39** [mehboss/CustomRecipes#62]
### What happened?

I have essential on my server  so i cant make any thing with [Recipes] i cant craft any thing  what should i do ?

### What was supposed to happen?

i must craft the item like havenbag
![WhatsApp Image 2024-11-26 at 2 03 08 PM](https://github.com/user-attachments/assets/705e0d6c-b7c4-4414-85f8-62ca4211aeaa)

### How do I reproduce this issue?

```bash
Just trying to craft items.
```

### Server Version

1.21.1

### Plugin Version

 1.9.7

### Server Mode

Online Mode

### Issue Confirmation

- [X] I have downloaded and tried the latest version of custom recipes and the issue still persists.
- [X] I have provided sufficient information for the issue to be replicated.

**Comment by ORZ39** [comment]
![Screenshot 2024-11-26 140348](https://github.com/user-attachments/assets/61ff355d-2dcd-491b-92e5-5abbeefed74a)

**Comment by mehboss** [comment]
This issue has been resolved in the latest update.
