### ISSUE TITLE
Plugin CustomRecipes 1.9.8 jar

### ISSUE THREAD

**Issue by Awwalin** [mehboss/CustomRecipes#64]
### What happened?

![problem 1](https://github.com/user-attachments/assets/31d8ea20-ccd7-408e-b404-1820015c056c)
![plugins 2](https://github.com/user-attachments/assets/9846bec6-78b5-41b5-9688-bea4a958657d)
![plugins 1](https://github.com/user-attachments/assets/4803ce3c-ac37-48c2-975f-3dde6f0dfab5)
![purpur](https://github.com/user-attachments/assets/c1978f16-722d-4d7e-8a4c-fb99d6088f2d)

i was putting all the plugin that were compatible from havenarena (spigot website)
and then i started the server, it worked just fine until i try to enter ther server in-game, so i went searching for solution online
and there's some website that said check for any custom recipes in plugins folder, so i kinda just delete the customrecipes 1.9.8 and its folder then i restart the server and i can enter normally in-game

### What was supposed to happen?

Enter the server like normal

### How do I reproduce this issue?

```bash
1.put the customrecipes 1.9.8 into plugin folder 
2.start the server
3.enter thr server in-game
4.and it happen
```

### Relevant log output

```shell
[17:49:01 INFO]: Awwalin joined the game
[17:49:01 INFO]: Awwalin[/124.13.211.201:56074] logged in with entity id 185 at ([Tester]7.1576493773138115, 65.0, -9.330987107048566)
[17:49:01 INFO]: Awwalin lost connection: Disconnected
[17:49:01 INFO]: Awwalin left the game
```

### Relevant file configuration

```shell
Config
https://pastebin.com/KxQ2iiHu
CursedPick
https://pastebin.com/fs9gCHZx
CursedSword
https://pastebin.com/bbJGXV3k
Havenbag
https://pastebin.com/hAHQbVBN
```

### Server Version

purpur 1.21.1

### Plugin Version

1.9.8

### Server Mode

Online Mode

### Issue Confirmation

- [X] I have downloaded and tried the latest version of custom recipes and the issue still persists.
- [X] I have provided sufficient information for the issue to be replicated.

**Comment by mehboss** [comment]
This issue has been resolved. The fix is quite simple -- just change the UNBREAKING:300 in the Enchantments section of the default recipe files to UNBREAKING:255. The server does not like enchants over 255.

You can find the update here
https://www.spigotmc.org/resources/%E2%96%BA%E2%96%BA-customrecipes-1-8-x-1-21-x-advanced-recipes-made-easy-%E2%97%84%E2%97%84.36925/update?update=573539

Thank you for reporting and bringing this to my attention
