### ISSUE TITLE
crafting book issue 

### ISSUE THREAD

**Issue by MummieSenpai** [mehboss/CustomRecipes#7]
**Server Version** paper-1.19.4-550.jar
**Plugin Version** CustomRecipes(v1.8.1).jar
**other plugins** Worldedit, worldguard
**issue**
first of all thank you for fixing the other issue so quickly you are doin great work. sadly with the fix that you pushed i encountered a new issue.

after updating from 1.8 to 1.8.1 of the plugin (using the latest version on spignot)
if i try to click an recipe using vanilla items it spits out an error in the console. 
a recipe with only custom items work fine. 

**server log after clicking gui button for "enchanted cobblestone" 
[Hastebin](https://hastebin.com/share/honovisuqu.ruby)

**Enchanted cobblestone yml**
[Hastebin](https://hastebin.com/share/ulowawahin.yaml)

**Comment by mehboss** [comment]
Ooops. 5s. I'll delete the update and reupload.

**Comment by mehboss** [comment]
Here you go. Let me know if this resolves the issue for you!
https://www.spigotmc.org/resources/%E2%96%BA%E2%96%BA-custom-crafting-recipes-1-8-x-1-20-x-per-recipe-perms-create-your-own-recipes-%E2%97%84%E2%97%84.36925/update?update=505935

**Comment by MummieSenpai** [comment]
this is indeed fixed now thank you for the quick response ;) 
a small oversight maybe but not critical the update ticker is complaining a bit but is unrelated to the fix you pushed

![javaw_cEDHmVH60Y](https://github.com/mehboss/CustomRecipes/assets/28273585/4029af6b-f95f-45ce-8e89-4f3d8528ec25)

**Comment by mehboss** [comment]
Awesome! And yeah, spigot server needs to communicate the new update to the minecraft server, it can be a few minutes behind sometimes. It should resolve itself once it realizes that there is in fact a 1.8.1 update available.
