### ISSUE TITLE
crafting bug multi item recipes(vanilla items)

### ISSUE THREAD

**Issue by MummieSenpai** [mehboss/CustomRecipes#9]
**Server Version** paper-1.20.1-55.jar
**Plugin Version** CustomRecipes(v1.8.1).jar
**issue**
when double clicking to craft a recipe using vanilla items (in this case coal) 
first recipe uses the correct amount (5 times 32 items in a + shape) but second craft only uses one item per slot. resulting in leftover coal and  crafted item. 
the yt link is a video of the issue
https://youtu.be/pmxqRRI0fcs

how to preproduce it is simply double clicking the item you want to craft. 
> enchanted coal config in this haste bin 
https://hastebin.com/share/oqunehuluz.yaml

**Comment by mehboss** [comment]
Just a bit more testing to do and then I will have this fixed in v.1.8.2. Shouldn't be much longer as I believe I have it resolved, I just want to test other items. Thank you for reporting!

**Comment by mehboss** [comment]
Hello again, I have done some testing. I believe this issue has been resolved. Please do not hesitate to let me know if you encounter any more issues. I will be attentive and fix them as soon as possible. Thank you for reporting and I apologize that this was overlooked!

Find the update here:
https://www.spigotmc.org/resources/%E2%96%BA%E2%96%BA-custom-crafting-recipes-1-8-x-1-20-x-per-recipe-perms-create-your-own-recipes-%E2%97%84%E2%97%84.36925/update?update=506500
